// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhGP54RFyMZwRhMgcX6IaOvXjFGj3W9Fc',
    appId: '1:1084947664349:web:87d28f269480b974f27a34',
    messagingSenderId: '1084947664349',
    projectId: 'movies-app-30fba',
    authDomain: 'movies-app-30fba.firebaseapp.com',
    storageBucket: 'movies-app-30fba.firebasestorage.app',
    measurementId: 'G-6MJ24RLE9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4z2r2z8LKYefIghhOWx1g3tzEst1In98',
    appId: '1:1084947664349:android:aa9a37fba3ec8871f27a34',
    messagingSenderId: '1084947664349',
    projectId: 'movies-app-30fba',
    storageBucket: 'movies-app-30fba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIbt3q1Wh3UIHiYi7STBYuDFpaH0Vn_nU',
    appId: '1:1084947664349:ios:41ce827270fd6727f27a34',
    messagingSenderId: '1084947664349',
    projectId: 'movies-app-30fba',
    storageBucket: 'movies-app-30fba.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIbt3q1Wh3UIHiYi7STBYuDFpaH0Vn_nU',
    appId: '1:1084947664349:ios:41ce827270fd6727f27a34',
    messagingSenderId: '1084947664349',
    projectId: 'movies-app-30fba',
    storageBucket: 'movies-app-30fba.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhGP54RFyMZwRhMgcX6IaOvXjFGj3W9Fc',
    appId: '1:1084947664349:web:edbbf5906f168198f27a34',
    messagingSenderId: '1084947664349',
    projectId: 'movies-app-30fba',
    authDomain: 'movies-app-30fba.firebaseapp.com',
    storageBucket: 'movies-app-30fba.firebasestorage.app',
    measurementId: 'G-2378KRPCVZ',
  );
}
